name: Merge main to test

on:
  push:
    branches:
      - main

jobs:
  merge_back_to_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Merge main -> test
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: test
          github_token: ${{ secrets.GITHUB_TOKEN }}
