name: "* Publish Test Web Client"

on:
  push:
    branches:
      - test

jobs:
  publish_test_web_client:
    name: Publish Test Web Client
    uses: ./.github/workflows/publish-ffxivvenues-web-client.yml
    with:
      branch: test
      tag: test
    secrets: inherit
