name: Publish Production Web Client

on:
  push:
    branches:
      - main

jobs:
  publish_production_web_client:
    uses: ./.github/workflows/publish-ffxivvenues-web-client.yml
    with:
      branch: main
      tag: latest
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_ACCESS_TOKEN }}