name: "* Publish Production Web Client"

on:
  push:
    branches:
      - main

jobs:
  publish_production_web_client:
    name: Publish Production Web Client
    uses: ./.github/workflows/publish-ffxivvenues-web-client.yml
    with:
      branch: main
      tag: latest
    secrets: inherit
